import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ProviderReactQuery} from "@/utils";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Videos upload",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProviderReactQuery>
          {children}
          <ToastContainer />
      </ProviderReactQuery>
      </body>
    </html>
  );
}
